"""Initial migration with 16 tables

Revision ID: 87ae9abb26b1
Revises: 
Create Date: 2025-11-18 13:14:45.479524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87ae9abb26b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('pais_sede_id', sa.Integer(), nullable=True),
    sa.Column('ciudad_sede', sa.String(length=100), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('capacidad_empresas', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_activo'), 'eventos', ['activo'], unique=False)
    op.create_index(op.f('ix_eventos_estado'), 'eventos', ['estado'], unique=False)
    op.create_index(op.f('ix_eventos_fecha_inicio'), 'eventos', ['fecha_inicio'], unique=False)
    op.create_index(op.f('ix_eventos_id'), 'eventos', ['id'], unique=False)
    op.create_table('kpis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('empresas_meta', sa.Integer(), nullable=True),
    sa.Column('empresas_actual', sa.Integer(), nullable=True),
    sa.Column('reuniones_meta', sa.Integer(), nullable=True),
    sa.Column('reuniones_actual', sa.Integer(), nullable=True),
    sa.Column('acuerdos_meta', sa.Integer(), nullable=True),
    sa.Column('acuerdos_actual', sa.Integer(), nullable=True),
    sa.Column('satisfaccion_meta', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('satisfaccion_actual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ocupacion_agenda', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('puntualidad', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nps', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha', name='kpis_fecha_unique')
    )
    op.create_index(op.f('ix_kpis_fecha'), 'kpis', ['fecha'], unique=False)
    op.create_index(op.f('ix_kpis_id'), 'kpis', ['id'], unique=False)
    op.create_table('mesas_tematicas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('sector_relacionado', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mesas_tematicas_activo'), 'mesas_tematicas', ['activo'], unique=False)
    op.create_index(op.f('ix_mesas_tematicas_id'), 'mesas_tematicas', ['id'], unique=False)
    op.create_table('paises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=3), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_paises_id'), 'paises', ['id'], unique=False)
    op.create_table('rutas_turisticas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('hora_salida', sa.Time(), nullable=True),
    sa.Column('hora_regreso', sa.Time(), nullable=True),
    sa.Column('capacidad_maxima', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('ubicacion_salida', sa.String(length=255), nullable=True),
    sa.Column('incluye', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rutas_turisticas_activo'), 'rutas_turisticas', ['activo'], unique=False)
    op.create_index(op.f('ix_rutas_turisticas_id'), 'rutas_turisticas', ['id'], unique=False)
    op.create_table('sectores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sectores_id'), 'sectores', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=True),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_activo'), 'usuarios', ['activo'], unique=False)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('bloques_horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.UUID(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('duracion_minutos', sa.Integer(), nullable=False),
    sa.Column('ubicacion', sa.String(length=100), nullable=True),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bloques_horarios_activo'), 'bloques_horarios', ['activo'], unique=False)
    op.create_index(op.f('ix_bloques_horarios_evento_id'), 'bloques_horarios', ['evento_id'], unique=False)
    op.create_index(op.f('ix_bloques_horarios_fecha'), 'bloques_horarios', ['fecha'], unique=False)
    op.create_index(op.f('ix_bloques_horarios_id'), 'bloques_horarios', ['id'], unique=False)
    op.create_table('empresas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('sitio_web', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('aprobada', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pais_id'], ['paises.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sectores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_aprobada'), 'empresas', ['aprobada'], unique=False)
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_index(op.f('ix_empresas_pais_id'), 'empresas', ['pais_id'], unique=False)
    op.create_index(op.f('ix_empresas_sector_id'), 'empresas', ['sector_id'], unique=False)
    op.create_table('curaduria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('ofrece', sa.Text(), nullable=True),
    sa.Column('busca', sa.Text(), nullable=True),
    sa.Column('objetivos', sa.Text(), nullable=True),
    sa.Column('capacidades', sa.Text(), nullable=True),
    sa.Column('notas_internas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', name='curaduria_empresa_unique')
    )
    op.create_index(op.f('ix_curaduria_empresa_id'), 'curaduria', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_curaduria_id'), 'curaduria', ['id'], unique=False)
    op.create_table('empresas_eventos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('evento_id', sa.UUID(), nullable=False),
    sa.Column('aprobada', sa.Boolean(), nullable=True),
    sa.Column('fecha_inscripcion', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'evento_id', name='empresa_evento_unique')
    )
    op.create_index(op.f('ix_empresas_eventos_aprobada'), 'empresas_eventos', ['aprobada'], unique=False)
    op.create_index(op.f('ix_empresas_eventos_empresa_id'), 'empresas_eventos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_empresas_eventos_evento_id'), 'empresas_eventos', ['evento_id'], unique=False)
    op.create_index(op.f('ix_empresas_eventos_id'), 'empresas_eventos', ['id'], unique=False)
    op.create_table('ndas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('firmada', sa.Boolean(), nullable=True),
    sa.Column('fecha_firma', sa.Date(), nullable=True),
    sa.Column('documento_url', sa.String(length=500), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ndas_empresa_id'), 'ndas', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_ndas_firmada'), 'ndas', ['firmada'], unique=False)
    op.create_index(op.f('ix_ndas_id'), 'ndas', ['id'], unique=False)
    op.create_index(op.f('ix_ndas_tipo'), 'ndas', ['tipo'], unique=False)
    op.create_table('participantes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('cargo', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('idioma', sa.String(length=2), nullable=True),
    sa.Column('requiere_interprete', sa.Boolean(), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('qr_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'email', name='email_unique_per_empresa')
    )
    op.create_index(op.f('ix_participantes_email'), 'participantes', ['email'], unique=False)
    op.create_index(op.f('ix_participantes_empresa_id'), 'participantes', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_participantes_id'), 'participantes', ['id'], unique=False)
    op.create_table('reuniones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bloque_id', sa.Integer(), nullable=False),
    sa.Column('empresa_a_id', sa.UUID(), nullable=False),
    sa.Column('empresa_b_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('requiere_interprete', sa.Boolean(), nullable=True),
    sa.Column('sala', sa.String(length=50), nullable=True),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('empresa_a_id != empresa_b_id', name='empresas_distintas'),
    sa.ForeignKeyConstraint(['bloque_id'], ['bloques_horarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_a_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['empresa_b_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bloque_id', 'empresa_a_id', name='reunion_bloque_unique'),
    sa.UniqueConstraint('bloque_id', 'empresa_b_id', name='reunion_bloque_unique_b')
    )
    op.create_index(op.f('ix_reuniones_bloque_id'), 'reuniones', ['bloque_id'], unique=False)
    op.create_index(op.f('ix_reuniones_empresa_a_id'), 'reuniones', ['empresa_a_id'], unique=False)
    op.create_index(op.f('ix_reuniones_empresa_b_id'), 'reuniones', ['empresa_b_id'], unique=False)
    op.create_index(op.f('ix_reuniones_estado'), 'reuniones', ['estado'], unique=False)
    op.create_index(op.f('ix_reuniones_id'), 'reuniones', ['id'], unique=False)
    op.create_table('seguimiento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('responsable', sa.String(length=255), nullable=True),
    sa.Column('fecha_compromiso', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('documentos_url', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seguimiento_empresa_id'), 'seguimiento', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_seguimiento_estado'), 'seguimiento', ['estado'], unique=False)
    op.create_index(op.f('ix_seguimiento_id'), 'seguimiento', ['id'], unique=False)
    op.create_index(op.f('ix_seguimiento_tipo'), 'seguimiento', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seguimiento_tipo'), table_name='seguimiento')
    op.drop_index(op.f('ix_seguimiento_id'), table_name='seguimiento')
    op.drop_index(op.f('ix_seguimiento_estado'), table_name='seguimiento')
    op.drop_index(op.f('ix_seguimiento_empresa_id'), table_name='seguimiento')
    op.drop_table('seguimiento')
    op.drop_index(op.f('ix_reuniones_id'), table_name='reuniones')
    op.drop_index(op.f('ix_reuniones_estado'), table_name='reuniones')
    op.drop_index(op.f('ix_reuniones_empresa_b_id'), table_name='reuniones')
    op.drop_index(op.f('ix_reuniones_empresa_a_id'), table_name='reuniones')
    op.drop_index(op.f('ix_reuniones_bloque_id'), table_name='reuniones')
    op.drop_table('reuniones')
    op.drop_index(op.f('ix_participantes_id'), table_name='participantes')
    op.drop_index(op.f('ix_participantes_empresa_id'), table_name='participantes')
    op.drop_index(op.f('ix_participantes_email'), table_name='participantes')
    op.drop_table('participantes')
    op.drop_index(op.f('ix_ndas_tipo'), table_name='ndas')
    op.drop_index(op.f('ix_ndas_id'), table_name='ndas')
    op.drop_index(op.f('ix_ndas_firmada'), table_name='ndas')
    op.drop_index(op.f('ix_ndas_empresa_id'), table_name='ndas')
    op.drop_table('ndas')
    op.drop_index(op.f('ix_empresas_eventos_id'), table_name='empresas_eventos')
    op.drop_index(op.f('ix_empresas_eventos_evento_id'), table_name='empresas_eventos')
    op.drop_index(op.f('ix_empresas_eventos_empresa_id'), table_name='empresas_eventos')
    op.drop_index(op.f('ix_empresas_eventos_aprobada'), table_name='empresas_eventos')
    op.drop_table('empresas_eventos')
    op.drop_index(op.f('ix_curaduria_id'), table_name='curaduria')
    op.drop_index(op.f('ix_curaduria_empresa_id'), table_name='curaduria')
    op.drop_table('curaduria')
    op.drop_index(op.f('ix_empresas_sector_id'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_pais_id'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_aprobada'), table_name='empresas')
    op.drop_table('empresas')
    op.drop_index(op.f('ix_bloques_horarios_id'), table_name='bloques_horarios')
    op.drop_index(op.f('ix_bloques_horarios_fecha'), table_name='bloques_horarios')
    op.drop_index(op.f('ix_bloques_horarios_evento_id'), table_name='bloques_horarios')
    op.drop_index(op.f('ix_bloques_horarios_activo'), table_name='bloques_horarios')
    op.drop_table('bloques_horarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_activo'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_sectores_id'), table_name='sectores')
    op.drop_table('sectores')
    op.drop_index(op.f('ix_rutas_turisticas_id'), table_name='rutas_turisticas')
    op.drop_index(op.f('ix_rutas_turisticas_activo'), table_name='rutas_turisticas')
    op.drop_table('rutas_turisticas')
    op.drop_index(op.f('ix_paises_id'), table_name='paises')
    op.drop_table('paises')
    op.drop_index(op.f('ix_mesas_tematicas_id'), table_name='mesas_tematicas')
    op.drop_index(op.f('ix_mesas_tematicas_activo'), table_name='mesas_tematicas')
    op.drop_table('mesas_tematicas')
    op.drop_index(op.f('ix_kpis_id'), table_name='kpis')
    op.drop_index(op.f('ix_kpis_fecha'), table_name='kpis')
    op.drop_table('kpis')
    op.drop_index(op.f('ix_eventos_id'), table_name='eventos')
    op.drop_index(op.f('ix_eventos_fecha_inicio'), table_name='eventos')
    op.drop_index(op.f('ix_eventos_estado'), table_name='eventos')
    op.drop_index(op.f('ix_eventos_activo'), table_name='eventos')
    op.drop_table('eventos')
    # ### end Alembic commands ###
